# Generated by Django 5.2.6 on 2025-09-30 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_create_at_task_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_at',
            new_name='create_at',
        ),
    ]
